apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: swift-kitura-app-monitored-knative
spec:
  template:
    spec:
      containers:
        - image: 'REGISTRY_URL/REGISTRY_NAMESPACE/IMAGE_NAME:BUILD_NUMBER'
          ports:
            - containerPort: 3000
